const cities = [
	{ name: "Bogotá", value: "bogota" },
	{ name: "Medellín", value: "medellin" },
	{ name: "Cali", value: "cali" },
	{ name: "Barranquilla", value: "barranquilla" },
	{ name: "Cartagena", value: "cartagena" },
	{ name: "Soacha", value: "soacha" },
	{ name: "Cúcuta", value: "cucuta" },
	{ name: "Soledad", value: "soledad" },
	{ name: "Bucaramanga", value: "bucaramanga" },
	{ name: "Bello", value: "bello" },
	{ name: "Valledupar", value: "valledupar" },
	{ name: "Villavicencio", value: "villavicencio" },
	{ name: "Santa Marta", value: "santa-marta" },
	{ name: "Ibagué", value: "ibague" },
	{ name: "Montería", value: "monteria" },
	{ name: "Pereira", value: "pereira" },
	{ name: "Manizales", value: "manizales" },
	{ name: "Pasto", value: "pasto" },
	{ name: "Neiva", value: "neiva" },
	{ name: "Palmira", value: "palmira" },
	{ name: "Popayán", value: "popayan" },
	{ name: "Buenaventura", value: "buenaventura" },
	{ name: "Armenia", value: "armenia" },
	{ name: "Floridablanca", value: "floridablanca" },
	{ name: "Sincelejo", value: "sincelejo" },
	{ name: "Itagüí", value: "itagui" },
	{ name: "Tumaco", value: "tumaco" },
	{ name: "Envigado", value: "envigado" },
	{ name: "Dosquebradas", value: "dosquebradas" },
	{ name: "Tuluá", value: "tulua" },
	{ name: "Barrancabermeja", value: "barrancabermeja" },
	{ name: "Riohacha", value: "riohacha" },
	{ name: "Uribia", value: "uribia" },
	{ name: "Maicao", value: "maicao" },
	{ name: "Piedecuesta", value: "piedecuesta" },
	{ name: "Tunja", value: "tunja" },
	{ name: "Yopal", value: "yopal" },
	{ name: "Florencia", value: "florencia" },
	{ name: "Girón", value: "giron" },
	{ name: "Facatativá", value: "facatativa" },
	{ name: "Jamundí", value: "jamundi" },
	{ name: "Fusagasugá", value: "fusagasuga" },
	{ name: "Mosquera", value: "mosquera" },
	{ name: "Chía", value: "chia" },
	{ name: "Zipaquirá", value: "zipaquira" },
	{ name: "Rionegro", value: "rionegro" },
	{ name: "Malambo", value: "malambo" },
	{ name: "Magangué", value: "magangue" },
	{ name: "Madrid", value: "madrid" },
	{ name: "Cartago", value: "cartago" },
	{ name: "Turbo", value: "turbo" },
	{ name: "Quibdó", value: "quibdo" },
	{ name: "Apartadó", value: "apartado" },
	{ name: "Sogamoso", value: "sogamoso" },
	{ name: "Ocaña", value: "ocana" },
	{ name: "Pitalito", value: "pitalito" },
	{ name: "Buga", value: "buga" },
	{ name: "Duitama", value: "duitama" },
	{ name: "Ciénaga", value: "cienaga" },
	{ name: "Aguachica", value: "aguachica" },
	{ name: "Girardot", value: "girardot" },
	{ name: "Lorica", value: "lorica" },
	{ name: "Turbaco", value: "turbaco" },
	{ name: "Ipiales", value: "ipiales" },
	{ name: "Funza", value: "funza" },
	{ name: "Santander de Quilichao", value: "santander-de-quilichao" },
	{ name: "Villa del Rosario", value: "villa-del-rosario" },
	{ name: "Sahagún", value: "sahagun" },
	{ name: "Yumbo", value: "yumbo" },
	{ name: "Cereté", value: "cerete" },
	{ name: "Sabanalarga", value: "sabanalarga" },
	{ name: "Cajicá", value: "cajica" },
	{ name: "Arauca", value: "arauca" },
	{ name: "Caucasia", value: "caucasia" },
	{ name: "Los Patios", value: "los-patios" },
	{ name: "Manaure", value: "manaure" },
	{ name: "Tierralta", value: "tierralta" },
	{ name: "Candelaria", value: "candelaria" },
	{ name: "Acacías", value: "acacias" },
	{ name: "Sabaneta", value: "sabaneta" },
	{ name: "Montelíbano", value: "montelibano" },
	{ name: "Caldas", value: "caldas" },
	{ name: "Copacabana", value: "copacabana" },
	{ name: "Cumaribo", value: "cumaribo" },
	{ name: "Santa Rosa de Cabal", value: "santa-rosa-de-cabal" },
	{ name: "La Estrella", value: "la-estrella" },
	{ name: "Calarcá", value: "calarca" },
	{ name: "Zona Bananera", value: "zona-bananera" },
	{ name: "Arjona", value: "arjona" },
	{ name: "La Dorada", value: "la-dorada" },
	{ name: "Garzón", value: "garzon" },
	{ name: "El Carmen de Bolívar", value: "el-carmen-de-bolivar" },
	{ name: "Corozal", value: "corozal" },
	{ name: "Fundación", value: "fundacion" },
	{ name: "Granada", value: "granada" },
	{ name: "El Banco", value: "el-banco" },
	{ name: "La Ceja", value: "la-ceja" },
	{ name: "Espinal", value: "espinal" },
	{ name: "Marinilla", value: "marinilla" },
	{ name: "Puerto Asís", value: "puerto-asis" },
	{ name: "Baranoa", value: "baranoa" },
	{ name: "Galapa", value: "galapa" },
	{ name: "Villamaría", value: "villamaria" },
	{ name: "Agustín Codazzi", value: "agustin-codazzi" },
	{ name: "Plato", value: "plato" },
	{ name: "Planeta Rica", value: "planeta-rica" },
	{ name: "Saravena", value: "saravena" },
	{ name: "El Carmen de Viboral", value: "el-carmen-de-viboral" },
	{ name: "La Plata", value: "la-plata" },
	{ name: "Chigorodó", value: "chigorodo" },
	{ name: "San Marcos", value: "san-marcos" },
	{ name: "Ciénaga de Oro", value: "cienaga-de-oro" },
	{ name: "Mocoa", value: "mocoa" },
	{ name: "San Gil", value: "san-gil" },
	{ name: "Guarne", value: "guarne" },
	{ name: "Tibú", value: "tibu" },
	{ name: "San José del Guaviare", value: "san-jose-del-guaviare" },
	{ name: "San Andrés", value: "san-andres" },
	{ name: "Florida", value: "florida" },
	{ name: "Chiquinquirá", value: "chiquinquira" },
	{ name: "Arauquita", value: "arauquita" },
	{ name: "El Cerrito", value: "el-cerrito" },
	{ name: "Girardota", value: "girardota" },
	{ name: "Barbosa", value: "barbosa" },
	{ name: "Barbacoas", value: "barbacoas" },
	{ name: "Riosucio", value: "riosucio" },
	{ name: "El Bagre", value: "el-bagre" },
	{ name: "Tuchín", value: "tuchin" },
	{ name: "Puerto Colombia", value: "puerto-colombia" },
	{ name: "Pamplona", value: "pamplona" },
	{ name: "El Tambo", value: "el-tambo" },
	{ name: "San Vicente del Caguán", value: "san-vicente-del-caguan" },
	{ name: "San Pelayo", value: "san-pelayo" },
	{ name: "Chinchiná", value: "chinchina" },
	{ name: "Carepa", value: "carepa" },
	{ name: "La Jagua de Ibirico", value: "la-jagua-de-ibirico" },
	{ name: "Riosucio", value: "riosucio" },
	{ name: "Leticia", value: "leticia" },
	{ name: "San Onofre", value: "san-onofre" },
	{ name: "San Juan del Cesar", value: "san-juan-del-cesar" },
	{ name: "Ubaté", value: "ubate" },
	{ name: "Tame", value: "tame" },
	{ name: "Chaparral", value: "chaparral" },
	{ name: "Sampués", value: "sampues" },
	{ name: "Tocancipá", value: "tocancipa" },
	{ name: "María La Baja", value: "maria-la-baja" },
];

export default cities;
